.gitignore, Source/ARA/ProcessorEditor.cpp, Source/DeepLearning/Model.h, Source/DeepLearning/WebModel.h
Only tested on windows. 
1. Open HARP, type a URL and click load
2. After loading, close the HARP UI
3. Reopen it. The URL should still be there.
=> fix issue with space url

.gitignore, Source/ARA/DocumentControllerSpecialisation.cpp, Source/ARA/DocumentControllerSpecialisation.h, Source/ARA/PlaybackRenderer.cpp, Source/ARA/PlaybackRenderer.h
Only tested on windows. If you want to check if it works on MacOS:
1. Make sure it builds successfully.
2. Load HARP, try adding and removing audio files to/from a track. 
3. After every addition/removal check the debugging messages. The playbackRenderers.size() should be the same as the number of audio files in your track.
=> fixes 67 - not tested in MacOs

Source/ARA/AudioModification.cpp, Source/ARA/AudioModification.h, Source/ARA/DocumentControllerSpecialisation.cpp, Source/ARA/ProcessorEditor.cpp, Source/WaveformCache/WaveformCache.h
Tested on Windows.
To test it in Mac, make sure the issues in #93 , as well as in #91 are fixed
=> Fixes waveform thumbnail issues + textBox focus improvements

src/MainComponent.h
Replaced modelpathTextBox with modelpathComboBox and other changes accordingly, options are currently hard coded in line :606
=> added dropdowns 

CMakeLists.txt, RELEASE.md, src/Main.cpp, src/MainComponent.h
- Save       : `cmd + s`
- Save As... : `cmd + shift + s`
- Open...    : `cmd + o`
- MenuBar --> "File" --> "About HARP" 
**NOTE**: On Mac, when testing the "save" functionality, "Apple Music" caches audio files and it might play a previous verison of the file. Use another media player if possible.
=> MenuBar actions (save, save as, open) + "about" dialog box

py/client/gradiojuce_client.py, src/MainComponent.h, src/WebModel.h
=> Handle empty audio file, gradio timeouts, better generic errors

src/MainComponent.h
Just a quick modification to remove MusicGen from the dropdown
=> removed MusicGen from dropdown

CMakeLists.txt, src/MainComponent.h, src/WebModel.h, src/gui/MultiButton.cpp, src/gui/MultiButton.h
1. Improved horizontal and vertical mouseWheel for moving/zooming audio thumbnail
2. followTransport is set to True by default
3. Added new error message for when the model url is empty
4. A new GUI element called MultiButton. Used for the single process/cancel button
5. A new play/stop button using the MultiButton class. 
6. DescriptionLabel height changes based on the number of text lines.
=> Various GUI changes

src/Main.cpp
=> Make debug file output optional

src/CtrlComponent.h, src/MainComponent.h, src/TitledTextBox.h
Add a little more space to the controls area and have multi-line text. Also make some more space for label text on sliders and text boxes.
=> Formatting changes

src/MainComponent.h
Puts a save button in the row with the play and open file buttons
=> Add save button

src/Main.cpp, src/MainComponent.h
For #198 . Checks if a file has been updated and prompts the user on whether to replace it.
=> Check if file more recently updated on window focus

README.md
=> Add Mixcraft in list of DAWs

src/MainComponent.h, src/ThreadPoolJob.h, src/WebModel.h, src/gradio/GradioClient.cpp, src/utils.h
The status2 in WebModel is still not correctly updated, but the overall functionality is good to go.
=> Timeout and Cancel Button fixed.

CMakeLists.txt, src/CtrlComponent.h, src/MainComponent.h, src/ThreadPoolJob.h, src/WebModel.h, src/gradio/GradioClient.cpp, src/gui/HoverableLabel.h, src/gui/ModelAuthorLabel.h, src/utils.h
- Dropdowns (Combobox)
- Checkboxes (ToggleButtons)
- New ModelAuthorLabel
- Improved resizing. FlexBoxes in MainComponent::resized()
- Improved input-controls positioning
=> Bring features from HARP 3.x into 2.x

CMakeLists.txt, src/MainComponent.h, src/media/MediaDisplayComponent.cpp, src/pianoroll/NoteGridComponent.cpp, src/pianoroll/NoteGridComponent.hpp, src/windows/AboutWindow.h
I have been hitting the following assertion errors:
- Closing HARP after opening the About HARP window: JUCE Assertion failure in juce_LeakedObjectDetector.h:92
- Opening a MIDI file with notes that are too short to display: JUCE Assertion failure in juce_GraphicsContext.cpp:137
- Dragging and dropping in Debug mode: JUCE Assertion failure in juce_linux_Windowing.cpp:800
These have all been fixed in this PR.
=> Simple fixes to address some assertion errors.

src/MainComponent.h, src/gui/CustomPathDialog.h, src/media/MediaDisplayComponent.cpp, src/media/OutputLabelComponent.cpp
Several bug fixes and improvements:
- Fixed close (X) button on CustomPathDialog.
- Improved interactions between clicking/dragging and labels.
- Rearranged some processing checks and fixed error message for file not loaded.
=> Fixes for some miscellaneous bugs.

src/WebModel.h, src/gradio/GradioClient.cpp
- Fixed URL for API calls to HF
- Removed outdated URL patch
- Added "meta" entry for file controls
=> Simple changes for using spaces deployed with gradio v5 in HARP.

src/HarpLogger.cpp, src/Main.cpp
I'm not sure if the new log path was intentional, but it was not consistent with our existing log.
=> Fixed other window titles and re-organized log paths.

src/MainComponent.h, src/errors.h, src/gradio/GradioClient.cpp, src/gradio/GradioClient.h
edits made in src/MainComponent.h
=> Added Login process to the UI
